---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: user
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: microservice_user:1.0
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URL
              value: mongodb://user-db:27017/user?replicaSet=rs0
            - name: WAIT_HOSTS
              value: user-db:27017
